version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports: 
     - "80:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
