version: "3.3"

services:

  application:
    build:
      context: ./application
    env_file:
      - .env

  postgres:
    build:
      context: ./postgres
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
    ports: 
     - "${NGINX_OUTER_PORT}:80"
